# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cTVEMVJ3JTybGK99KgcHbIVb9ORtdwCD
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

print("OpenCV version:", cv2.__version__)

pip install opencv-contrib-python

pip install opencv-python-headless

import cv2

if hasattr(cv2, 'CascadeClassifier'):
    print("cv2.CascadeClassifier is available!")
else:
    print("cv2.CascadeClassifier is NOT available. Please ensure opencv-contrib-python is installed and the runtime has been restarted.")

uploaded = files.upload()
image_paths = list(uploaded.keys())
print("Uploaded files:", image_paths)

!pip install dlib
!pip install mediapipe
!pip install mtcnn
!pip install face_recognition

import dlib

# Initialize dlib's face detector
detector = dlib.get_frontal_face_detector()

# Download the pre-trained CNN face detection model
!wget http://dlib.net/files/mmod_human_face_detector.dat

print("Downloaded mmod_human_face_detector.dat")

!wget http://dlib.net/files/mmod_human_face_detector.dat.bz2

!bunzip2 mmod_human_face_detector.dat.bz2

print("Downloaded and decompressed mmod_human_face_detector.dat")

# Initialize dlib's CNN face detector
cnn_detector = dlib.cnn_face_detection_model_v1("mmod_human_face_detector.dat")

# Reassign the 'detector' variable to the CNN detector
detector = cnn_detector

print("Dlib detector updated to CNN-based model.")

def detect_faces(image_path):
    img_bgr = cv2.imread(image_path)

    if img_bgr is None:
        raise ValueError(f"Could not read image: {image_path}")

    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)

    # Use dlib's CNN detector to find faces
    # It returns a list of mmod_rect objects.
    dlib_faces = detector(gray, 1) # The '1' means upsample the image 1 time

    faces = []
    for mmod_rect in dlib_faces:
        # Extract the dlib.rectangle from the mmod_rect object
        dlib_rect = mmod_rect.rect
        x = dlib_rect.left()
        y = dlib_rect.top()
        w = dlib_rect.width()
        h = dlib_rect.height()
        faces.append((x, y, w, h))

    output = img_rgb.copy()

    for (x, y, w, h) in faces:
        cv2.rectangle(output, (x, y), (x+w, y+h), (255, 0, 0), 3)

    return img_rgb, gray, output, faces

for image_path in image_paths:
    img_rgb, gray, output, faces = detect_faces(image_path)

    plt.figure(figsize=(14,5))

    plt.subplot(1,3,1)
    plt.imshow(img_rgb)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(gray, cmap="gray")
    plt.title("Grayscale Image")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(output)
    plt.title(f"Detected Faces: {len(faces)}")
    plt.axis("off")

    plt.show()

    print(f"Image: {image_path}")
    print("Faces detected:", len(faces))
    print("-" * 40)

# Select first image for parameter testing
test_image = image_paths[0]

# The dlib detector doesn't use scaleFactor or minNeighbors directly,
# but you could explore dlib's detector parameters if you wanted to tune it.
# For now, we will simply call the function without these arguments.

# Original parameter_settings that are no longer applicable to dlib detector
# parameter_settings = [
#     (1.05, 3),
#     (1.1, 5),
#     (1.2, 5),
#     (1.3, 6)
# ]

# We will just run the detection once as these parameters don't apply to dlib.
# If you wish to tune dlib, you would modify the dlib_faces = detector(gray, 1) line
# For example, changing the upsampling value '1'.

img_rgb, gray, output, faces = detect_faces(test_image)

plt.figure(figsize=(6,5))
plt.imshow(output)
plt.title(f"Detected Faces: {len(faces)}")
plt.axis("off")
plt.show()

import cv2
import dlib
import matplotlib.pyplot as plt
from IPython.display import Image, display
import base64
from PIL import Image as PIL_Image
import io

# Ensure the dlib detector is initialized (from previous cells) with the CNN model
# The 'detector' variable should already be assigned to the cnn_detector from cell b9a2079c.

# IMPORTANT: Update this path to your video file.
# The example uses one of your previously uploaded video files.
video_path = '/content/WhatsApp Video 2024-07-11 at 14.58.31.mp4' # Or '/content/WhatsApp Video 2024-09-03 at 10.07.15.mp4'

cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print(f"Error: Could not open video file {video_path}")
else:
    print(f"Successfully opened video file: {video_path}")
    frame_count = 0
    # Process a limited number of frames for demonstration to avoid long execution times
    max_frames_to_process = 50

    while True:
        ret, frame = cap.read()
        if not ret:
            break # End of video

        frame_count += 1
        if frame_count > max_frames_to_process:
            break

        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Use dlib's CNN detector to find faces
        # The CNN detector takes a grayscale image and an optional upsampling parameter.
        # It returns a list of mmod_rect objects.
        dlib_faces_cnn = detector(gray, 1) # '1' means upsample the image 1 time

        detected_faces_boxes = []
        for mmod_rect in dlib_faces_cnn:
            # Extract the dlib.rectangle from the mmod_rect object
            dlib_rect = mmod_rect.rect
            x = dlib_rect.left()
            y = dlib_rect.top()
            w = dlib_rect.width()
            h = dlib_rect.height()
            detected_faces_boxes.append((x, y, w, h))

        output_frame = img_rgb.copy()
        for (x, y, w, h) in detected_faces_boxes:
            cv2.rectangle(output_frame, (x, y), (x+w, y+h), (255, 0, 0), 3)

        # Display a few frames with detected faces using Matplotlib
        if frame_count % 5 == 0 or frame_count == 1: # Display every 5th frame and the first
            print(f"--- Frame {frame_count}, Faces detected: {len(detected_faces_boxes)} ---")
            plt.figure(figsize=(8, 6))
            plt.imshow(output_frame)
            plt.title(f"Frame {frame_count} (Faces: {len(detected_faces_boxes)})")
            plt.axis('off')
            plt.show()

    cap.release()
    print("Video processing finished with Dlib CNN detector.")

"""### Dlib Face Detection on Video (simulating webcam)

Since live webcam is challenging in Colab, we'll demonstrate `dlib` face detection on a video file. Make sure you have uploaded a video file to your Colab environment (e.g., named `input_video.mp4`).
"""

import cv2
import dlib
import matplotlib.pyplot as plt
from IPython.display import Image, display
import base64
from PIL import Image as PIL_Image
import io

# Ensure the dlib detector is initialized (from previous cells)
# detector = dlib.get_frontal_face_detector()

# You need to upload a video file, e.g., 'input_video.mp4'
video_path = '/content/WhatsApp Video 2024-09-03 at 10.07.15.mp4'  # <<< CHANGE THIS TO YOUR UPLOADED VIDEO FILE NAME

# Attempt to open the video file
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print(f"Error: Could not open video file {video_path}")
else:
    print(f"Successfully opened video file: {video_path}")
    frame_count = 0
    max_frames_to_process = 20 # Process a limited number of frames for demonstration

    while True:
        ret, frame = cap.read()
        if not ret:
            break # End of video

        frame_count += 1
        if frame_count > max_frames_to_process: # Stop after processing enough frames
            break

        # Convert frame to RGB for dlib and plotting
        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Use dlib's detector to find faces
        dlib_faces = detector(gray, 1) # '1' means upsample the image 1 time

        detected_faces_boxes = []

        for mmod_rect in dlib_faces:
            # Extract the dlib.rectangle from the mmod_rect object
            dlib_rect = mmod_rect.rect
            x = dlib_rect.left()
            y = dlib_rect.top()
            w = dlib_rect.width()
            h = dlib_rect.height()
            detected_faces_boxes.append((x, y, w, h))

        # Draw rectangles on the RGB frame
        output_frame = img_rgb.copy()
        for (x, y, w, h) in detected_faces_boxes:
            cv2.rectangle(output_frame, (x, y), (x+w, y+h), (255, 0, 0), 3)

        # Display a few frames with detected faces
        if frame_count % 5 == 0 or frame_count == 1: # Display every 5th frame and the first
            print(f"--- Frame {frame_count}, Faces detected: {len(detected_faces_boxes)} ---")
            plt.figure(figsize=(8, 6))
            plt.imshow(output_frame)
            plt.title(f"Frame {frame_count} (Faces: {len(detected_faces_boxes)})")
            plt.axis('off')
            plt.show()

    cap.release()
    print("Video processing finished.")

import cv2
import dlib
import matplotlib.pyplot as plt
from IPython.display import Image, display
import base64
from PIL import Image as PIL_Image
import io

# Ensure the dlib detector is initialized (from previous cells)
# detector = dlib.get_frontal_face_detector()

# You need to upload a video file, e.g., 'input_video.mp4'
video_path = '/content/WhatsApp Video 2024-09-03 at 10.07.15.mp4'  # <<< CHANGE THIS TO YOUR UPLOADED VIDEO FILE NAME

# Attempt to open the video file
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print(f"Error: Could not open video file {video_path}")
else:
    print(f"Successfully opened video file: {video_path}")
    frame_count = 0
    max_frames_to_process = 20 # Process a limited number of frames for demonstration

    while True:
        ret, frame = cap.read()
        if not ret:
            break # End of video

        frame_count += 1
        if frame_count > max_frames_to_process: # Stop after processing enough frames
            break

        # Convert frame to RGB for dlib and plotting
        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Use dlib's detector to find faces
        dlib_faces = detector(gray, 1) # '1' means upsample the image 1 time

        detected_faces_boxes = []
        for mmod_rect in dlib_faces:
            # Extract the dlib.rectangle from the mmod_rect object
            dlib_rect = mmod_rect.rect
            x = dlib_rect.left()
            y = dlib_rect.top()
            w = dlib_rect.width()
            h = dlib_rect.height()
            detected_faces_boxes.append((x, y, w, h))

        # Draw rectangles on the RGB frame
        output_frame = img_rgb.copy()
        for (x, y, w, h) in detected_faces_boxes:
            cv2.rectangle(output_frame, (x, y), (x+w, y+h), (255, 0, 0), 3)

        # Display a few frames with detected faces
        if frame_count % 5 == 0 or frame_count == 1: # Display every 5th frame and the first
            print(f"--- Frame {frame_count}, Faces detected: {len(detected_faces_boxes)} ---")
            plt.figure(figsize=(8, 6))
            plt.imshow(output_frame)
            plt.title(f"Frame {frame_count} (Faces: {len(detected_faces_boxes)})")
            plt.axis('off')
            plt.show()

    cap.release()
    print("Video processing finished.")

import cv2
import dlib
import matplotlib.pyplot as plt
from IPython.display import Image, display
import base64
from PIL import Image as PIL_Image
import io

# Ensure the dlib detector is initialized (from previous cells)
# detector = dlib.get_frontal_face_detector()

# You need to upload a video file, e.g., 'input_video.mp4'
video_path = '/content/WhatsApp Video 2024-07-11 at 14.58.31.mp4'  # <<< CHANGE THIS TO YOUR UPLOADED VIDEO FILE NAME

# Attempt to open the video file
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print(f"Error: Could not open video file {video_path}")
else:
    print(f"Successfully opened video file: {video_path}")
    frame_count = 0
    max_frames_to_process = 50 # Process a limited number of frames for demonstration (increased from 20)

    while True:
        ret, frame = cap.read()
        if not ret:
            break # End of video

        frame_count += 1
        if frame_count > max_frames_to_process: # Stop after processing enough frames
            break

        # Convert frame to RGB for dlib and plotting
        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Use dlib's detector to find faces
        dlib_faces = detector(gray, 2) # '2' means upsample the image 2 times (increased from 1)

        detected_faces_boxes = []
        for mmod_rect in dlib_faces:
            # Extract the dlib.rectangle from the mmod_rect object
            dlib_rect = mmod_rect.rect
            x = dlib_rect.left()
            y = dlib_rect.top()
            w = dlib_rect.width()
            h = dlib_rect.height()
            detected_faces_boxes.append((x, y, w, h))

        # Draw rectangles on the RGB frame
        output_frame = img_rgb.copy()
        for (x, y, w, h) in detected_faces_boxes:
            cv2.rectangle(output_frame, (x, y), (x+w, y+h), (255, 0, 0), 3)

        # Display a few frames with detected faces
        if frame_count % 5 == 0 or frame_count == 1: # Display every 5th frame and the first
            print(f"--- Frame {frame_count}, Faces detected: {len(detected_faces_boxes)} ---")
            plt.figure(figsize=(8, 6))
            plt.imshow(output_frame)
            plt.title(f"Frame {frame_count} (Faces: {len(detected_faces_boxes)})")
            plt.axis('off')
            plt.show()

    cap.release()
    print("Video processing finished.")

import cv2
import dlib
import matplotlib.pyplot as plt
from IPython.display import Image, display
import base64
from PIL import Image as PIL_Image
import io

# Ensure the dlib detector is initialized (from previous cells) with the CNN model
# detector = dlib.cnn_face_detection_model_v1("mmod_human_face_detector.dat")
# The 'detector' variable should already be assigned to the cnn_detector from the previous cell.

video_path = '/content/WhatsApp Video 2024-07-11 at 14.58.31.mp4'  # <<< This should be updated if you upload a different video

cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print(f"Error: Could not open video file {video_path}")
else:
    print(f"Successfully opened video file: {video_path}")
    frame_count = 0
    max_frames_to_process = 50 # Process a limited number of frames for demonstration

    while True:
        ret, frame = cap.read()
        if not ret:
            break # End of video

        frame_count += 1
        if frame_count > max_frames_to_process: # Stop after processing enough frames
            break

        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Use dlib's CNN detector to find faces
        # The CNN detector takes a single image and an optional upsampling parameter.
        # It returns a list of mmod_rect objects.
        dlib_faces_cnn = detector(gray, 1) # '1' means upsample the image 1 time

        detected_faces_boxes = []
        for mmod_rect in dlib_faces_cnn:
            # Extract the dlib.rectangle from the mmod_rect object
            dlib_rect = mmod_rect.rect
            x = dlib_rect.left()
            y = dlib_rect.top()
            w = dlib_rect.width()
            h = dlib_rect.height()
            detected_faces_boxes.append((x, y, w, h))

        output_frame = img_rgb.copy()
        for (x, y, w, h) in detected_faces_boxes:
            cv2.rectangle(output_frame, (x, y), (x+w, y+h), (255, 0, 0), 3)

        if frame_count % 5 == 0 or frame_count == 1:
            print(f"--- Frame {frame_count}, Faces detected: {len(detected_faces_boxes)} ---")
            plt.figure(figsize=(8, 6))
            plt.imshow(output_frame)
            plt.title(f"Frame {frame_count} (Faces: {len(detected_faces_boxes)})")
            plt.axis('off')
            plt.show()

    cap.release()
    print("Video processing finished.")